[build-system]
requires = ["setuptools>=84.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gov-gh"
version = "0.5.0"
description = "Python package for the gov-gh repository"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
  { name = "Office for National Statistics" }
]
dependencies = [
    "gql[requests]>=4.0.0",
    "pydantic>=2.13.4",
]

[dependency-groups]
dev = [
  "pytest>=8.3.0",
  "pytest-cov>=5.0.0",
  "pre-commit>=4.0.0",
  "ruff>=0.6.0"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["gov_gh*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
addopts = "-q"

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.codespell]
ignore-words = "configs/.codespell-ignore-words.txt"
skip = ".git,*.lock,*.svg"
quiet-level = 2
